version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
  frontend:
    image: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000