import { Avatar,Box,CssBaseline,Divider,List,ListItem,ListItemIcon,ListItemText,Paper,Toolbar,Typography,TextField,FormControlLabel,Checkbox,Alert,Button,Grid } from '@mui/material';
import { useSelector } from "react-redux";

const drawerWidth = 720;

const AccountManageProfile = () => {
  const username = useSelector((state) => state.auth.value.username);

  return (
    <Paper 
      elevation={2} 
      sx={{ 
        width: drawerWidth, 
        flexShrink: 0 
      }}
    >
      <Box>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>

        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography><Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>

        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        <Typography>
          Profile
        </Typography>
        
      </Box>
    </Paper>
  );
}

export default AccountManageProfile;