export const URL_LOGIN = ''
export const URL_REGISTER = '/api/users/register-new-student'
export const URL_CATEGORIES = '/api/categories'
export const URL_CREATE_NEW_COURSE = '/api/instructors/course'
export const URL_GET_CREATED_COURSE = '/api/instructors/incomplete-courses'
export const URL_CREATE_PAR_FOR_COURSE_PIC = '/api/instructors/incomplete-courses/picture/pre-authenticated-request'
export const URL_SAVE_COURSE_PICTURE = '/api/instructors/incomplete-courses/picture'

export const URL_GET_OVERVIEW_COURSE_ID = '/api/overview/'
export const URL_GET_HOME_PREVIEW_CATEGORY = '/api/preview/'
export const URL_GET_PREVIEW_COURSE_ID = '/api/preview/course/'
export const URL_GET_PREVIEW_MY_COURSE = '/api/preview/my-course'